#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'Sensing'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 4

# The Active Message type associated with this message.
AM_TYPE = -1

class Sensing(tinyos.message.Message.Message):
    # Create a new Sensing of size 4.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=4):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <Sensing> \n"
        try:
            s += "  [product_id=0x%x]\n" % (self.get_product_id())
        except:
            pass
        try:
            s += "  [temp=0x%x]\n" % (self.get_temp())
        except:
            pass
        try:
            s += "  [node_id=0x%x]\n" % (self.get_node_id())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: product_id
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'product_id' is signed (False).
    #
    def isSigned_product_id(self):
        return False
    
    #
    # Return whether the field 'product_id' is an array (False).
    #
    def isArray_product_id(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'product_id'
    #
    def offset_product_id(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'product_id'
    #
    def offsetBits_product_id(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'product_id'
    #
    def get_product_id(self):
        return self.getUIntElement(self.offsetBits_product_id(), 8, 1)
    
    #
    # Set the value of the field 'product_id'
    #
    def set_product_id(self, value):
        self.setUIntElement(self.offsetBits_product_id(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'product_id'
    #
    def size_product_id(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'product_id'
    #
    def sizeBits_product_id(self):
        return 8
    
    #
    # Accessor methods for field: temp
    #   Field type: int
    #   Offset (bits): 8
    #   Size (bits): 16
    #

    #
    # Return whether the field 'temp' is signed (False).
    #
    def isSigned_temp(self):
        return False
    
    #
    # Return whether the field 'temp' is an array (False).
    #
    def isArray_temp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'temp'
    #
    def offset_temp(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'temp'
    #
    def offsetBits_temp(self):
        return 8
    
    #
    # Return the value (as a int) of the field 'temp'
    #
    def get_temp(self):
        return self.getUIntElement(self.offsetBits_temp(), 16, 1)
    
    #
    # Set the value of the field 'temp'
    #
    def set_temp(self, value):
        self.setUIntElement(self.offsetBits_temp(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'temp'
    #
    def size_temp(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'temp'
    #
    def sizeBits_temp(self):
        return 16
    
    #
    # Accessor methods for field: node_id
    #   Field type: short
    #   Offset (bits): 24
    #   Size (bits): 8
    #

    #
    # Return whether the field 'node_id' is signed (False).
    #
    def isSigned_node_id(self):
        return False
    
    #
    # Return whether the field 'node_id' is an array (False).
    #
    def isArray_node_id(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'node_id'
    #
    def offset_node_id(self):
        return (24 / 8)
    
    #
    # Return the offset (in bits) of the field 'node_id'
    #
    def offsetBits_node_id(self):
        return 24
    
    #
    # Return the value (as a short) of the field 'node_id'
    #
    def get_node_id(self):
        return self.getUIntElement(self.offsetBits_node_id(), 8, 1)
    
    #
    # Set the value of the field 'node_id'
    #
    def set_node_id(self, value):
        self.setUIntElement(self.offsetBits_node_id(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'node_id'
    #
    def size_node_id(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'node_id'
    #
    def sizeBits_node_id(self):
        return 8
    
